version: "3.8"
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: Contrasenia123
            POSTGRES_DB: db_postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data
        restart: always

volumes:
    postgres-db:
